apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-pod
  template:
    metadata:
      labels:
        app: auth-service-pod
    spec:
      containers:
        - name: auth-service-pod
          image: gcr.io/social-363908/auth-service:latest
          env:
          - name: TWILIO_ACCOUNT_SID
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: twilio-account-sid
          - name: TWILIO_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key:  twilio-auth-token
          - name: TWILIO_PHONE_NUMBER
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: twilio-phone-number
          - name: REDIS_AUTH_PASS
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: redis-auth-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-password
          - name: AUTH_JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: auth-jwt-secret-key
          - name: REDIS_HOST
            value: redis-0.redis.default.svc.cluster.local
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-internal
spec:
  selector:
    app: auth-service-pod
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000