apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-deployment
  labels:
    app: api-gateway-service-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service-pod
  template:
    metadata:
      labels:
        app: api-gateway-service-pod
    spec:
      containers:
        - name: api-gateway-service-pod
          image: gcr.io/social-363908/api-gateway-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: CHAT_SERVICE_HOST
              value: chat-service-internal.default.svc.cluster.local
            - name: AUTH_SERVICE_HOST
              value: auth-service-internal.default.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000