apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cache-pv-claim-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: premium-rwo

---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: redis-cache-pv-claim-2
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 2Gi
    storageClassName: premium-rwo