apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
  labels:
    app: chat-service-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service-pod
  template:
    metadata:
      labels:
        app: chat-service-pod
    spec:
      containers:
        - name: chat-service-pod
          image: gcr.io/social-363908/chat-service:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-internal
spec:
  selector:
    app: chat-service-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000